const actionTypes = {
  ON_LOG_IN_OUT: 'ON_LOG_IN_OUT',
  ON_ERROR: 'ON_ERROR',
  ON_EDIT_FAVORITES: 'ON_EDIT_FAVORITES',
  IMPORT_PREREQUISITES: 'IMPORT_PREREQUISITES',
  ON_INPUT_SEARCH: 'ON_INPUT_SEARCH'
};

export default actionTypes;